openapi: 3.1.0
info:
  title: Sustainability Goal Planner
  description: |-
    This project is a sustainability goal planner application built using Ruby on Rails with React webpacker setup. The application allows to follow goal progresses over time.
  version: 1.0.0
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
  - url: http://localhost:3000/api/v1
tags:
  - name: goal
  - name: progress
paths:
  /goals:
    post:
      tags:
        - goal
      summary: Add a new goal
      operationId: addGoal
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Goal'
      responses:
        '200':
          description: Created
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    allOf:
                      - $ref: '#/components/schemas/GoalResponse'   
        '422':
          description: Unprocessable Content
    get:
      tags:
        - goal
      summary: retrieve all the goals data
      operationId: getGoals
      responses:
        '200':
          description: Created
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      type: object
                      allOf:
                        - $ref: '#/components/schemas/GoalResponse'   
        '422':
          description: Unprocessable Content
  /goals/{id}:
    delete:
      tags:
        - goal
      summary: Delete a goal by ID
      operationId: deleteGoal
      responses:
        '204':
          description: No Content
        '404':
          description: Not Found
    parameters:
        - name: id
          in: path
          required: true
          description: The ID of the goal to be deleted
          schema:
            type: integer
            format: int64
  /progresses:
    post:
      tags:
        - progress
      summary: Log progress for a goal
      operationId: logProgress
      requestBody:
        description: The progress entry to be logged
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Progress'
      responses:
        '200':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProgressResponse'
        '422':
          description: Unprocessable Content
  /progresses/{id}:
    delete:
      tags:
        - progress
      summary: Delete a progress entry by ID
      operationId: deleteProgress
      parameters:
        - name: id
          in: path
          required: true
          description: The ID of the progress entry to be deleted
          schema:
            type: integer
            format: int64
      responses:
        '204':
          description: No Content
        '404':
          description: Not Found

components:
  schemas:
    Goal:
      type: object
      properties:
        id:
            type: integer
            description: The autogenerated ID of the progress entry
        goal_name:
          type: string
          description: The name of the goal
        target_reduction:
          type: integer
          description: The target reduction value
        target_unit:
          type: string
          description: The unit for the target reduction
        start_date:
          type: string
          format: date
          description: The start date of the goal
        end_date:
          type: string
          format: date
          description: The end date of the goal
      required:
        - goal_name
        - target_reduction
        - target_unit
        - start_date
        - end_date
    GoalResponse:
      type: object
      properties:
        id:
          type: integer
        type:
          type: string
        attributes:
          allOf:
            - $ref: '#/components/schemas/Goal'
            - type: object
              properties:
                current_progresses:
                  type: integer
        relationships:
          type: object
          properties:
            progresses:
              type: object
              properties:
                data:
                  type: array
    Progress:
        type: object
        properties:
          id:
            type: integer
            description: The autogenerated ID of the progress entry
          goal_id:
            type: integer
            description: The ID of the associated goal
          entry_date:
            type: string
            format: date
            description: The date of the progress entry
          achieved_reduction:
            type: integer
            description: The amount of achieved reduction
          notes:
            type: string
            description: Additional notes about the progress
        required:
          - goal_id
          - entry_date
          - achieved_reduction
          - notes
    ProgressResponse:
      type: object
      properties:
        id:
          type: integer
        type:
          type: string
        attributes:
          allOf:
            - $ref: '#/components/schemas/Progress'